//! Additional telecommand metadata selected by the mission command database.

use crate::{CommandSpec, DataType, FieldSpec};

const REFERENCE_ROTATION_ANGLE_COMMAND_FIELDS: &[FieldSpec] = &[
    FieldSpec {
        offset_bits: 0,
        length_bits: 32,
        name: "Rotation Angle Command",
        data_type: DataType::Float,
        description: "Rotation Angle Command. (Unit of measure is [deg])",
        scale: None,
        unit: None,
        enum_table: None,
    },
];

const DISABLE_MAGNETIC_RWL_MOMENTUM_MANAGEMENT_COMMAND_FIELDS: &[FieldSpec] = &[
    FieldSpec {
        offset_bits: 0,
        length_bits: 16,
        name: "Duration",
        data_type: DataType::Uint,
        description: "Duration for which to disable RWL momentum management. (Unit of measure is [s])",
        scale: None,
        unit: None,
        enum_table: None,
    },
];

const REFERENCE_PARAMETERS_FOR_FMC_SCAN_COMMAND_FIELDS: &[FieldSpec] = &[
    FieldSpec {
        offset_bits: 0,
        length_bits: 8,
        name: "FMC Scanning Factor",
        data_type: DataType::Enum,
        description: "FMC Scanning Factor. Possible values are in Table 13",
        scale: None,
        unit: None,
        enum_table: Some("table_13"),
    },
    FieldSpec {
        offset_bits: 8,
        length_bits: 32,
        name: "FMC Roll command",
        data_type: DataType::Float,
        description: "RPY Roll command. (Unit of measure is [deg])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 40,
        length_bits: 32,
        name: "FMC Centre Time (seconds)",
        data_type: DataType::Uint,
        description: "Unix time seconds at FMC target centre. (Unit of measure is [s])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 72,
        length_bits: 32,
        name: "FMC Center Time (nanoseconds)",
        data_type: DataType::Uint,
        description: "Unix time nanoseconds at FMC target centre. (Unit of measure is [ns])",
        scale: None,
        unit: None,
        enum_table: None,
    },
];

const REFERENCE_IRC_VECTOR_COMMAND_FIELDS: &[FieldSpec] = &[
    FieldSpec {
        offset_bits: 0,
        length_bits: 32,
        name: "Commanded ECI pointing vector X component",
        data_type: DataType::Float,
        description: "Commanded ECI pointing vector X component",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 32,
        length_bits: 32,
        name: "Commanded ECI pointing vector Y component",
        data_type: DataType::Float,
        description: "Commanded ECI pointing vector Y component",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 64,
        length_bits: 32,
        name: "Commanded ECI pointing vector Z component",
        data_type: DataType::Float,
        description: "Commanded ECI pointing vector Z component",
        scale: None,
        unit: None,
        enum_table: None,
    },
];

const REFERENCE_LLH_TARGET_COMMAND_COMMAND_FIELDS: &[FieldSpec] = &[
    FieldSpec {
        offset_bits: 0,
        length_bits: 32,
        name: "Target latitude command",
        data_type: DataType::Float,
        description: "Target latitude command. (Unit of measure is [deg])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 32,
        length_bits: 32,
        name: "Target longitude command",
        data_type: DataType::Float,
        description: "Target longitude command. (Unit of measure is [deg])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 64,
        length_bits: 32,
        name: "Target altitude command",
        data_type: DataType::Float,
        description: "Target altitude command. (Unit of measure is [km])",
        scale: None,
        unit: None,
        enum_table: None,
    },
];

const TARGET_SATELLITE_ORBIT_PARAMETER_CONFIGURATION_COMMAND_FIELDS: &[FieldSpec] = &[
    FieldSpec {
        offset_bits: 0,
        length_bits: 64,
        name: "Orbit epoch",
        data_type: DataType::Double,
        description: "Orbit epoch. (Unit of measure is [yyddd.ssssssss])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 64,
        length_bits: 64,
        name: "Orbit inclination",
        data_type: DataType::Double,
        description: "Orbit inclination. (Unit of measure is [deg])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 128,
        length_bits: 64,
        name: "Orbit RAAN",
        data_type: DataType::Double,
        description: "Orbit RAAN. (Unit of measure is [deg])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 192,
        length_bits: 64,
        name: "Orbit eccentricity",
        data_type: DataType::Double,
        description: "Orbit eccentricity",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 256,
        length_bits: 64,
        name: "Orbit argument of perigee",
        data_type: DataType::Double,
        description: "Orbit argument of perigee. (Unit of measure is [deg])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 320,
        length_bits: 64,
        name: "Orbit mean anomaly",
        data_type: DataType::Double,
        description: "Orbit mean anomaly. (Unit of measure is [deg])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 384,
        length_bits: 64,
        name: "Orbit mean motion",
        data_type: DataType::Double,
        description: "Orbit mean motion. (Unit of measure is [orbits/day])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 448,
        length_bits: 64,
        name: "Orbit B-star drag term",
        data_type: DataType::Double,
        description: "Orbit B-star drag term",
        scale: None,
        unit: None,
        enum_table: None,
    },
];

const SIMULATION_RAW_SENSOR_TELEMETRY_COMMAND_FIELDS: &[FieldSpec] = &[
    FieldSpec {
        offset_bits: 0,
        length_bits: 32,
        name: "Time integer seconds",
        data_type: DataType::Uint,
        description: "Unix time integer seconds. (Unit of measure is [s])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 32,
        length_bits: 32,
        name: "Time nanoseconds",
        data_type: DataType::Uint,
        description: "Unix time fraction nanoseconds. (Unit of measure is [ns])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 64,
        length_bits: 16,
        name: "FSS0 raw centroid X",
        data_type: DataType::Int,
        description: "FSS0 raw centroid X. Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*100.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 80,
        length_bits: 16,
        name: "FSS0 raw centroid Y",
        data_type: DataType::Int,
        description: "FSS0 raw centroid Y. Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*100.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 96,
        length_bits: 16,
        name: "FSS1 raw centroid X",
        data_type: DataType::Int,
        description: "FSS1 raw centroid X. Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*100.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 112,
        length_bits: 16,
        name: "FSS1 raw centroid Y",
        data_type: DataType::Int,
        description: "FSS1 raw centroid Y. Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*100.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 128,
        length_bits: 16,
        name: "FSS2 raw centroid X",
        data_type: DataType::Int,
        description: "FSS2 raw centroid X. Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*100.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 144,
        length_bits: 16,
        name: "FSS2 raw centroid Y",
        data_type: DataType::Int,
        description: "FSS2 raw centroid Y. Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*100.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 160,
        length_bits: 16,
        name: "FSS3 raw centroid X",
        data_type: DataType::Int,
        description: "FSS3 raw centroid X. Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*100.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 176,
        length_bits: 16,
        name: "FSS3 raw centroid Y",
        data_type: DataType::Int,
        description: "FSS3 raw centroid Y. Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*100.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 192,
        length_bits: 16,
        name: "CSS0 raw measurement",
        data_type: DataType::Uint,
        description: "CSS0 raw measurement",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 208,
        length_bits: 16,
        name: "CSS1 raw measurement",
        data_type: DataType::Uint,
        description: "CSS1 raw measurement",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 224,
        length_bits: 16,
        name: "CSS2 raw measurement",
        data_type: DataType::Uint,
        description: "CSS2 raw measurement",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 240,
        length_bits: 16,
        name: "CSS3 raw measurement",
        data_type: DataType::Uint,
        description: "CSS3 raw measurement",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 256,
        length_bits: 16,
        name: "CSS4 raw measurement",
        data_type: DataType::Uint,
        description: "CSS4 raw measurement",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 272,
        length_bits: 16,
        name: "CSS5 raw measurement",
        data_type: DataType::Uint,
        description: "CSS5 raw measurement",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 288,
        length_bits: 16,
        name: "CSS6 raw measurement",
        data_type: DataType::Uint,
        description: "CSS6 raw measurement",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 304,
        length_bits: 16,
        name: "CSS7 raw measurement",
        data_type: DataType::Uint,
        description: "CSS7 raw measurement",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 320,
        length_bits: 16,
        name: "CSS8 raw measurement",
        data_type: DataType::Uint,
        description: "CSS8 raw measurement",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 336,
        length_bits: 16,
        name: "CSS9 raw measurement",
        data_type: DataType::Uint,
        description: "CSS9 raw measurement",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 352,
        length_bits: 16,
        name: "MAG0 raw vector X component",
        data_type: DataType::Int,
        description: "MAG0 raw vector X component. Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*100.0 (formatted value is in [uT] units)",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 368,
        length_bits: 16,
        name: "MAG0 raw vector Y component",
        data_type: DataType::Int,
        description: "MAG0 raw vector Y component. Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*100.0 (formatted value is in [uT] units)",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 384,
        length_bits: 16,
        name: "MAG0 raw vector Z component",
        data_type: DataType::Int,
        description: "MAG0 raw vector Z component. Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*100.0 (formatted value is in [uT] units)",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 400,
        length_bits: 16,
        name: "MAG1 raw vector X component",
        data_type: DataType::Int,
        description: "MAG1 raw vector X component. Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*100.0 (formatted value is in [uT] units)",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 416,
        length_bits: 16,
        name: "MAG1 raw vector Y component",
        data_type: DataType::Int,
        description: "MAG1 raw vector Y component. Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*100.0 (formatted value is in [uT] units)",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 432,
        length_bits: 16,
        name: "MAG1 raw vector Z component",
        data_type: DataType::Int,
        description: "MAG1 raw vector Z component. Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*100.0 (formatted value is in [uT] units)",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 448,
        length_bits: 32,
        name: "GYR0 raw rate X component",
        data_type: DataType::Float,
        description: "GYR0 raw rate X component. (Unit of measure is [degps])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 480,
        length_bits: 32,
        name: "GYR0 raw rate Y component",
        data_type: DataType::Float,
        description: "GYR0 raw rate Y component. (Unit of measure is [degps])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 512,
        length_bits: 32,
        name: "GYR0 raw rate Z component",
        data_type: DataType::Float,
        description: "GYR0 raw rate Z component. (Unit of measure is [degps])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 544,
        length_bits: 32,
        name: "GYR1 raw rate X component",
        data_type: DataType::Float,
        description: "GYR1 raw rate X component. (Unit of measure is [degps])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 576,
        length_bits: 32,
        name: "GYR1 raw rate Y component",
        data_type: DataType::Float,
        description: "GYR1 raw rate Y component. (Unit of measure is [degps])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 608,
        length_bits: 32,
        name: "GYR1 raw rate Z component",
        data_type: DataType::Float,
        description: "GYR1 raw rate Z component. (Unit of measure is [degps])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 640,
        length_bits: 16,
        name: "HSS0 raw elevation angle",
        data_type: DataType::Int,
        description: "HSS0 raw elevation angle. Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*100.0 (formatted value is in [deg] units)",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 656,
        length_bits: 16,
        name: "HSS0 raw rotation angle",
        data_type: DataType::Int,
        description: "HSS0 raw rotation angle. Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*100.0 (formatted value is in [deg] units)",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 672,
        length_bits: 16,
        name: "HSS1 raw elevation angle",
        data_type: DataType::Int,
        description: "HSS1 raw elevation angle. Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*100.0 (formatted value is in [deg] units)",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 688,
        length_bits: 16,
        name: "HSS1 raw rotation angle",
        data_type: DataType::Int,
        description: "HSS1 raw rotation angle. Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*100.0 (formatted value is in [deg] units)",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 704,
        length_bits: 16,
        name: "STR0 measured vector 0 X component",
        data_type: DataType::Int,
        description: "STR0 measured vector 0 X component (sensor frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 720,
        length_bits: 16,
        name: "STR0 measured vector 0 Y component",
        data_type: DataType::Int,
        description: "STR0 measured vector 0 Y component (sensor frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 736,
        length_bits: 16,
        name: "STR0 measured vector 0 Z component",
        data_type: DataType::Int,
        description: "STR0 measured vector 0 Z component (sensor frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 752,
        length_bits: 16,
        name: "STR0 measured vector 1 X component",
        data_type: DataType::Int,
        description: "STR0 measured vector 1 X component (sensor frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 768,
        length_bits: 16,
        name: "STR0 measured vector 1 Y component",
        data_type: DataType::Int,
        description: "STR0 measured vector 1 Y component (sensor frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 784,
        length_bits: 16,
        name: "STR0 measured vector 1 Z component",
        data_type: DataType::Int,
        description: "STR0 measured vector 1 Z component (sensor frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 800,
        length_bits: 16,
        name: "STR0 measured vector 2 X component",
        data_type: DataType::Int,
        description: "STR0 measured vector 2 X component (sensor frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 816,
        length_bits: 16,
        name: "STR0 measured vector 2 Y component",
        data_type: DataType::Int,
        description: "STR0 measured vector 2 Y component (sensor frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 832,
        length_bits: 16,
        name: "STR0 measured vector 2 Z component",
        data_type: DataType::Int,
        description: "STR0 measured vector 2 Z component (sensor frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 848,
        length_bits: 16,
        name: "STR0 modelled vector 0 X component",
        data_type: DataType::Int,
        description: "STR0 modelled vector 0 X component (IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 864,
        length_bits: 16,
        name: "STR0 modelled vector 0 Y component",
        data_type: DataType::Int,
        description: "STR0 modelled vector 0 Y component (IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 880,
        length_bits: 16,
        name: "STR0 modelled vector 0 Z component",
        data_type: DataType::Int,
        description: "STR0 modelled vector 0 Z component (IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 896,
        length_bits: 16,
        name: "STR0 modelled vector 1 X component",
        data_type: DataType::Int,
        description: "STR0 modelled vector 1 X component (IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 912,
        length_bits: 16,
        name: "STR0 modelled vector 1 Y component",
        data_type: DataType::Int,
        description: "STR0 modelled vector 1 Y component (IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 928,
        length_bits: 16,
        name: "STR0 modelled vector 1 Z component",
        data_type: DataType::Int,
        description: "STR0 modelled vector 1 Z component (IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 944,
        length_bits: 16,
        name: "STR0 modelled vector 2 X component",
        data_type: DataType::Int,
        description: "STR0 modelled vector 2 X component (IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 960,
        length_bits: 16,
        name: "STR0 modelled vector 2 Y component",
        data_type: DataType::Int,
        description: "STR0 modelled vector 2 Y component (IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 976,
        length_bits: 16,
        name: "STR0 modelled vector 2 Z component",
        data_type: DataType::Int,
        description: "STR0 modelled vector 2 Z component (IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 992,
        length_bits: 16,
        name: "STR0 measured quaternion Q0 (sensor to IRC frame)",
        data_type: DataType::Int,
        description: "STR0 measured quaternion Q0 (sensor to IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1008,
        length_bits: 16,
        name: "STR0 measured quaternion Q1 (sensor to IRC frame)",
        data_type: DataType::Int,
        description: "STR0 measured quaternion Q1 (sensor to IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1024,
        length_bits: 16,
        name: "STR0 measured quaternion Q2 (sensor to IRC frame)",
        data_type: DataType::Int,
        description: "STR0 measured quaternion Q2 (sensor to IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1040,
        length_bits: 16,
        name: "STR0 measured quaternion Q3 (sensor to IRC frame)",
        data_type: DataType::Int,
        description: "STR0 measured quaternion Q3 (sensor to IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1056,
        length_bits: 8,
        name: "STR0 number of identified stars",
        data_type: DataType::Uint,
        description: "STR0 number of identified stars",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1064,
        length_bits: 16,
        name: "STR1 measured vector 0 X component",
        data_type: DataType::Int,
        description: "STR1 measured vector 0 X component (sensor frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1080,
        length_bits: 16,
        name: "STR1 measured vector 0 Y component",
        data_type: DataType::Int,
        description: "STR1 measured vector 0 Y component (sensor frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1096,
        length_bits: 16,
        name: "STR1 measured vector 0 Z component",
        data_type: DataType::Int,
        description: "STR1 measured vector 0 Z component (sensor frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1112,
        length_bits: 16,
        name: "STR1 measured vector 1 X component",
        data_type: DataType::Int,
        description: "STR1 measured vector 1 X component (sensor frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1128,
        length_bits: 16,
        name: "STR1 measured vector 1 Y component",
        data_type: DataType::Int,
        description: "STR1 measured vector 1 Y component (sensor frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1144,
        length_bits: 16,
        name: "STR1 measured vector 1 Z component",
        data_type: DataType::Int,
        description: "STR1 measured vector 1 Z component (sensor frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1160,
        length_bits: 16,
        name: "STR1 measured vector 2 X component",
        data_type: DataType::Int,
        description: "STR1 measured vector 2 X component (sensor frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1176,
        length_bits: 16,
        name: "STR1 measured vector 2 Y component",
        data_type: DataType::Int,
        description: "STR1 measured vector 2 Y component (sensor frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1192,
        length_bits: 16,
        name: "STR1 measured vector 2 Z component",
        data_type: DataType::Int,
        description: "STR1 measured vector 2 Z component (sensor frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1208,
        length_bits: 16,
        name: "STR1 modelled vector 0 X component",
        data_type: DataType::Int,
        description: "STR1 modelled vector 0 X component (IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1224,
        length_bits: 16,
        name: "STR1 modelled vector 0 Y component",
        data_type: DataType::Int,
        description: "STR1 modelled vector 0 Y component (IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1240,
        length_bits: 16,
        name: "STR1 modelled vector 0 Z component",
        data_type: DataType::Int,
        description: "STR1 modelled vector 0 Z component (IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1256,
        length_bits: 16,
        name: "STR1 modelled vector 1 X component",
        data_type: DataType::Int,
        description: "STR1 modelled vector 1 X component (IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1272,
        length_bits: 16,
        name: "STR1 modelled vector 1 Y component",
        data_type: DataType::Int,
        description: "STR1 modelled vector 1 Y component (IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1288,
        length_bits: 16,
        name: "STR1 modelled vector 1 Z component",
        data_type: DataType::Int,
        description: "STR1 modelled vector 1 Z component (IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1304,
        length_bits: 16,
        name: "STR1 modelled vector 2 X component",
        data_type: DataType::Int,
        description: "STR1 modelled vector 2 X component (IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1320,
        length_bits: 16,
        name: "STR1 modelled vector 2 Y component",
        data_type: DataType::Int,
        description: "STR1 modelled vector 2 Y component (IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1336,
        length_bits: 16,
        name: "STR1 modelled vector 2 Z component",
        data_type: DataType::Int,
        description: "STR1 modelled vector 2 Z component (IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1352,
        length_bits: 16,
        name: "STR1 measured quaternion Q0 (sensor to IRC frame)",
        data_type: DataType::Int,
        description: "STR1 measured quaternion Q0 (sensor to IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1368,
        length_bits: 16,
        name: "STR1 measured quaternion Q1 (sensor to IRC frame)",
        data_type: DataType::Int,
        description: "STR1 measured quaternion Q1 (sensor to IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1384,
        length_bits: 16,
        name: "STR1 measured quaternion Q2 (sensor to IRC frame)",
        data_type: DataType::Int,
        description: "STR1 measured quaternion Q2 (sensor to IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1400,
        length_bits: 16,
        name: "STR1 measured quaternion Q3 (sensor to IRC frame)",
        data_type: DataType::Int,
        description: "STR1 measured quaternion Q3 (sensor to IRC frame). Raw parameter value is obtained using the formula: (raw parameter) = (formatted value)*10000.0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1416,
        length_bits: 8,
        name: "STR1 number of identified stars",
        data_type: DataType::Uint,
        description: "STR1 number of identified stars",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1424,
        length_bits: 32,
        name: "GNSS Time integer seconds",
        data_type: DataType::Uint,
        description: "GNSS Unix time integer seconds. (Unit of measure is [s])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1456,
        length_bits: 32,
        name: "GNSS Time nanoseconds",
        data_type: DataType::Uint,
        description: "GNSS Unix time fraction nanoseconds. (Unit of measure is [ns])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1488,
        length_bits: 32,
        name: "Satellite position vector X component (GNSS frame)",
        data_type: DataType::Int,
        description: "Satellite position vector X component (GNSS frame). (Unit of measure is [cm])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1520,
        length_bits: 32,
        name: "Satellite position vector Y component (GNSS frame)",
        data_type: DataType::Int,
        description: "Satellite position vector Y component (GNSS frame). (Unit of measure is [cm])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1552,
        length_bits: 32,
        name: "Satellite position vector Z component (GNSS frame)",
        data_type: DataType::Int,
        description: "Satellite position vector Z component (GNSS frame). (Unit of measure is [cm])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1584,
        length_bits: 32,
        name: "Satellite velocity vector X component (GNSS frame)",
        data_type: DataType::Int,
        description: "Satellite velocity vector X component (GNSS frame). (Unit of measure is [cm/s])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1616,
        length_bits: 32,
        name: "Satellite velocity vector Y component (GNSS frame)",
        data_type: DataType::Int,
        description: "Satellite velocity vector Y component (GNSS frame). (Unit of measure is [cm/s])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1648,
        length_bits: 32,
        name: "Satellite velocity vector Z component (GNSS frame)",
        data_type: DataType::Int,
        description: "Satellite velocity vector Z component (GNSS frame). (Unit of measure is [cm/s])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1680,
        length_bits: 32,
        name: "ExtSensor0 raw measurement float 0",
        data_type: DataType::Float,
        description: "ExtSensor0 raw measurement float 0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1712,
        length_bits: 32,
        name: "ExtSensor0 raw measurement float 1",
        data_type: DataType::Float,
        description: "ExtSensor0 raw measurement float 1",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1744,
        length_bits: 32,
        name: "ExtSensor0 raw measurement float 2",
        data_type: DataType::Float,
        description: "ExtSensor0 raw measurement float 2",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1776,
        length_bits: 32,
        name: "ExtSensor0 raw measurement float 3",
        data_type: DataType::Float,
        description: "ExtSensor0 raw measurement float 3",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1808,
        length_bits: 32,
        name: "ExtSensor0 raw measurement float 4",
        data_type: DataType::Float,
        description: "ExtSensor0 raw measurement float 4",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1840,
        length_bits: 32,
        name: "ExtSensor0 raw measurement float 5",
        data_type: DataType::Float,
        description: "ExtSensor0 raw measurement float 5",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1872,
        length_bits: 32,
        name: "ExtSensor1 raw measurement float 0",
        data_type: DataType::Float,
        description: "ExtSensor1 raw measurement float 0",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1904,
        length_bits: 32,
        name: "ExtSensor1 raw measurement float 1",
        data_type: DataType::Float,
        description: "ExtSensor1 raw measurement float 1",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1936,
        length_bits: 32,
        name: "ExtSensor1 raw measurement float 2",
        data_type: DataType::Float,
        description: "ExtSensor1 raw measurement float 2",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1968,
        length_bits: 32,
        name: "ExtSensor1 raw measurement float 3",
        data_type: DataType::Float,
        description: "ExtSensor1 raw measurement float 3",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2000,
        length_bits: 32,
        name: "ExtSensor1 raw measurement float 4",
        data_type: DataType::Float,
        description: "ExtSensor1 raw measurement float 4",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2032,
        length_bits: 32,
        name: "ExtSensor1 raw measurement float 5",
        data_type: DataType::Float,
        description: "ExtSensor1 raw measurement float 5",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2064,
        length_bits: 32,
        name: "RWL0 raw speed measurement",
        data_type: DataType::Float,
        description: "RWL0 raw speed measurement. (Unit of measure is [rpm])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2096,
        length_bits: 32,
        name: "RWL1 raw speed measurement",
        data_type: DataType::Float,
        description: "RWL1 raw speed measurement. (Unit of measure is [rpm])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2128,
        length_bits: 32,
        name: "RWL2 raw speed measurement",
        data_type: DataType::Float,
        description: "RWL2 raw speed measurement. (Unit of measure is [rpm])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2160,
        length_bits: 32,
        name: "RWL3 raw speed measurement",
        data_type: DataType::Float,
        description: "RWL3 raw speed measurement. (Unit of measure is [rpm])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2192,
        length_bits: 1,
        name: "FSS0 valid flag",
        data_type: DataType::Bool,
        description: "FSS0 valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2193,
        length_bits: 1,
        name: "FSS1 valid flag",
        data_type: DataType::Bool,
        description: "FSS1 valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2194,
        length_bits: 1,
        name: "FSS2 valid flag",
        data_type: DataType::Bool,
        description: "FSS2 valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2195,
        length_bits: 1,
        name: "FSS3 valid flag",
        data_type: DataType::Bool,
        description: "FSS3 valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2196,
        length_bits: 1,
        name: "CSS valid flag",
        data_type: DataType::Bool,
        description: "CSS valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2197,
        length_bits: 1,
        name: "MAG0 valid flag",
        data_type: DataType::Bool,
        description: "MAG0 valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2198,
        length_bits: 1,
        name: "MAG1 valid flag",
        data_type: DataType::Bool,
        description: "MAG1 valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2199,
        length_bits: 1,
        name: "GYR0 valid flag",
        data_type: DataType::Bool,
        description: "GYR0 valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2200,
        length_bits: 1,
        name: "GYR1 valid flag",
        data_type: DataType::Bool,
        description: "GYR1 valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2201,
        length_bits: 1,
        name: "HSS0 valid flag",
        data_type: DataType::Bool,
        description: "HSS0 valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2202,
        length_bits: 1,
        name: "HSS1 valid flag",
        data_type: DataType::Bool,
        description: "HSS1 valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2203,
        length_bits: 1,
        name: "STR0 valid flag",
        data_type: DataType::Bool,
        description: "STR0 valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2204,
        length_bits: 1,
        name: "STR1 valid flag",
        data_type: DataType::Bool,
        description: "STR1 valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2205,
        length_bits: 1,
        name: "GNSS valid flag",
        data_type: DataType::Bool,
        description: "GNSS valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2206,
        length_bits: 1,
        name: "GNSS new nav message flag",
        data_type: DataType::Bool,
        description: "GNSS new flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2207,
        length_bits: 1,
        name: "ExtSensor0 valid flag",
        data_type: DataType::Bool,
        description: "ExtSensor0 valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2208,
        length_bits: 1,
        name: "ExtSensor1 valid flag",
        data_type: DataType::Bool,
        description: "ExtSensor1 valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2209,
        length_bits: 1,
        name: "RWL0 valid flag",
        data_type: DataType::Bool,
        description: "RWL0 valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2210,
        length_bits: 1,
        name: "RWL1 valid flag",
        data_type: DataType::Bool,
        description: "RWL1 valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2211,
        length_bits: 1,
        name: "RWL2 valid flag",
        data_type: DataType::Bool,
        description: "RWL2 valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2212,
        length_bits: 1,
        name: "RWL3 valid flag",
        data_type: DataType::Bool,
        description: "RWL3 valid flag",
        scale: None,
        unit: None,
        enum_table: None,
    },
];

const TRANSFER_FRAME_COMMAND_FIELDS: &[FieldSpec] = &[
    FieldSpec {
        offset_bits: 0,
        length_bits: 16,
        name: "Next Frame Number",
        data_type: DataType::Uint,
        description: "Number of next frame to be transferred",
        scale: None,
        unit: None,
        enum_table: None,
    },
];

const FILE_TRANSFER_SETUP_COMMAND_FIELDS: &[FieldSpec] = &[
    FieldSpec {
        offset_bits: 0,
        length_bits: 8,
        name: "Op Code",
        data_type: DataType::Enum,
        description: "Operation to perform. Possible values are in Table 55",
        scale: None,
        unit: None,
        enum_table: Some("table_55"),
    },
    FieldSpec {
        offset_bits: 8,
        length_bits: 8,
        name: "File",
        data_type: DataType::Enum,
        description: "File to target. Possible values are in Table 56",
        scale: None,
        unit: None,
        enum_table: Some("table_56"),
    },
    FieldSpec {
        offset_bits: 16,
        length_bits: 8,
        name: "Node",
        data_type: DataType::Enum,
        description: "OpCode = Upgrade: Node to upgrade in conjunction with SerialInt. Possible values are in Table 57",
        scale: None,
        unit: None,
        enum_table: Some("table_57"),
    },
    FieldSpec {
        offset_bits: 24,
        length_bits: 32,
        name: "Serial Number Integer",
        data_type: DataType::Uint,
        description: "OpCode = Upgrade: Serial Number Integer of node to upgrade in conjunction with Node",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 56,
        length_bits: 8,
        name: "Program",
        data_type: DataType::Enum,
        description: "OpCode = Upgrade: The Program Type to upgrade with. Possible values are in Table 58",
        scale: None,
        unit: None,
        enum_table: Some("table_58"),
    },
    FieldSpec {
        offset_bits: 64,
        length_bits: 32,
        name: "File Size",
        data_type: DataType::Uint,
        description: "Size of target file: Only used to confirm setup.. (Unit of measure is [Bytes])",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 96,
        length_bits: 4,
        name: "Force Port",
        data_type: DataType::Enum,
        description: "OpCode = Upgrade: Force that the node on this port is upgraded In the event that the node is not discoverable.. Possible values are in Table 59",
        scale: None,
        unit: None,
        enum_table: Some("table_59"),
    },
    FieldSpec {
        offset_bits: 100,
        length_bits: 4,
        name: "",
        data_type: DataType::Padding,
        description: "Reserved.",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 104,
        length_bits: 1024,
        name: "File Meta Data",
        data_type: DataType::Array,
        description: "CubeSpace File Meta Data. May be less than allocated size (padding required)",
        scale: None,
        unit: None,
        enum_table: None,
    },
];

const PASS_THROUGH_TCTLM_COMMAND_FIELDS: &[FieldSpec] = &[
    FieldSpec {
        offset_bits: 0,
        length_bits: 8,
        name: "Target Node",
        data_type: DataType::Enum,
        description: "Target Node. Possible values are in Table 61",
        scale: None,
        unit: None,
        enum_table: Some("table_61"),
    },
];

const PORT_MAP_COMMAND_FIELDS: &[FieldSpec] = &[
    FieldSpec {
        offset_bits: 0,
        length_bits: 8,
        name: "Node Type: Sensor 1",
        data_type: DataType::Enum,
        description: "Sensor 1 port - Node type identifier. Possible values are in Table 57",
        scale: None,
        unit: None,
        enum_table: Some("table_57"),
    },
    FieldSpec {
        offset_bits: 8,
        length_bits: 8,
        name: "Abstract Node Type: Sensor 1",
        data_type: DataType::Enum,
        description: "Sensor 1 port - Abstract Node type identifier. Possible values are in Table 61",
        scale: None,
        unit: None,
        enum_table: Some("table_61"),
    },
    FieldSpec {
        offset_bits: 16,
        length_bits: 32,
        name: "Serial Number Integer: Sensor 1",
        data_type: DataType::Uint,
        description: "Sensor 1 port - Serial Number Integer Respresentation",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 48,
        length_bits: 32,
        name: "Address: Sensor 1",
        data_type: DataType::Uint,
        description: "Sensor 1 port - CAN Address",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 80,
        length_bits: 8,
        name: "Node Type: Sensor 2",
        data_type: DataType::Enum,
        description: "Sensor 2 port - Node type identifier. Possible values are in Table 57",
        scale: None,
        unit: None,
        enum_table: Some("table_57"),
    },
    FieldSpec {
        offset_bits: 88,
        length_bits: 8,
        name: "Abstract Node Type: Sensor 2",
        data_type: DataType::Enum,
        description: "Sensor 2 port - Abstract Node type identifier. Possible values are in Table 61",
        scale: None,
        unit: None,
        enum_table: Some("table_61"),
    },
    FieldSpec {
        offset_bits: 96,
        length_bits: 32,
        name: "Serial Number Integer: Sensor 2",
        data_type: DataType::Uint,
        description: "Sensor 2 port - Serial Number Integer Respresentation",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 128,
        length_bits: 32,
        name: "Address: Sensor 2",
        data_type: DataType::Uint,
        description: "Sensor 2 port - CAN Address",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 160,
        length_bits: 8,
        name: "Node Type: Sensor 3",
        data_type: DataType::Enum,
        description: "Sensor 3 port - Node type identifier. Possible values are in Table 57",
        scale: None,
        unit: None,
        enum_table: Some("table_57"),
    },
    FieldSpec {
        offset_bits: 168,
        length_bits: 8,
        name: "Abstract Node Type: Sensor 3",
        data_type: DataType::Enum,
        description: "Sensor 3 port - Abstract Node type identifier. Possible values are in Table 61",
        scale: None,
        unit: None,
        enum_table: Some("table_61"),
    },
    FieldSpec {
        offset_bits: 176,
        length_bits: 32,
        name: "Serial Number Integer: Sensor 3",
        data_type: DataType::Uint,
        description: "Sensor 3 port - Serial Number Integer Respresentation",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 208,
        length_bits: 32,
        name: "Address: Sensor 3",
        data_type: DataType::Uint,
        description: "Sensor 3 port - CAN Address",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 240,
        length_bits: 8,
        name: "Node Type: Sensor 4",
        data_type: DataType::Enum,
        description: "Sensor 4 port - Node type identifier. Possible values are in Table 57",
        scale: None,
        unit: None,
        enum_table: Some("table_57"),
    },
    FieldSpec {
        offset_bits: 248,
        length_bits: 8,
        name: "Abstract Node Type: Sensor 4",
        data_type: DataType::Enum,
        description: "Sensor 4 port - Abstract Node type identifier. Possible values are in Table 61",
        scale: None,
        unit: None,
        enum_table: Some("table_61"),
    },
    FieldSpec {
        offset_bits: 256,
        length_bits: 32,
        name: "Serial Number Integer: Sensor 4",
        data_type: DataType::Uint,
        description: "Sensor 4 port - Serial Number Integer Respresentation",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 288,
        length_bits: 32,
        name: "Address: Sensor 4",
        data_type: DataType::Uint,
        description: "Sensor 4 port - CAN Address",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 320,
        length_bits: 8,
        name: "Node Type: Sensor 5",
        data_type: DataType::Enum,
        description: "Sensor 5 port - Node type identifier. Possible values are in Table 57",
        scale: None,
        unit: None,
        enum_table: Some("table_57"),
    },
    FieldSpec {
        offset_bits: 328,
        length_bits: 8,
        name: "Abstract Node Type: Sensor 5",
        data_type: DataType::Enum,
        description: "Sensor 5 port - Abstract Node type identifier. Possible values are in Table 61",
        scale: None,
        unit: None,
        enum_table: Some("table_61"),
    },
    FieldSpec {
        offset_bits: 336,
        length_bits: 32,
        name: "Serial Number Integer: Sensor 5",
        data_type: DataType::Uint,
        description: "Sensor 5 port - Serial Number Integer Respresentation",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 368,
        length_bits: 32,
        name: "Address: Sensor 5",
        data_type: DataType::Uint,
        description: "Sensor 5 port - CAN Address",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 400,
        length_bits: 8,
        name: "Node Type: Sensor 6",
        data_type: DataType::Enum,
        description: "Sensor 6 port - Node type identifier. Possible values are in Table 57",
        scale: None,
        unit: None,
        enum_table: Some("table_57"),
    },
    FieldSpec {
        offset_bits: 408,
        length_bits: 8,
        name: "Abstract Node Type: Sensor 6",
        data_type: DataType::Enum,
        description: "Sensor 6 port - Abstract Node type identifier. Possible values are in Table 61",
        scale: None,
        unit: None,
        enum_table: Some("table_61"),
    },
    FieldSpec {
        offset_bits: 416,
        length_bits: 32,
        name: "Serial Number Integer: Sensor 6",
        data_type: DataType::Uint,
        description: "Sensor 6 port - Serial Number Integer Respresentation",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 448,
        length_bits: 32,
        name: "Address: Sensor 6",
        data_type: DataType::Uint,
        description: "Sensor 6 port - CAN Address",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 480,
        length_bits: 8,
        name: "Node Type: Sensor 7",
        data_type: DataType::Enum,
        description: "Sensor 7 port - Node type identifier. Possible values are in Table 57",
        scale: None,
        unit: None,
        enum_table: Some("table_57"),
    },
    FieldSpec {
        offset_bits: 488,
        length_bits: 8,
        name: "Abstract Node Type: Sensor 7",
        data_type: DataType::Enum,
        description: "Sensor 7 port - Abstract Node type identifier. Possible values are in Table 61",
        scale: None,
        unit: None,
        enum_table: Some("table_61"),
    },
    FieldSpec {
        offset_bits: 496,
        length_bits: 32,
        name: "Serial Number Integer: Sensor 7",
        data_type: DataType::Uint,
        description: "Sensor 7 port - Serial Number Integer Respresentation",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 528,
        length_bits: 32,
        name: "Address: Sensor 7",
        data_type: DataType::Uint,
        description: "Sensor 7 port - CAN Address",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 560,
        length_bits: 8,
        name: "Node Type: Sensor 8",
        data_type: DataType::Enum,
        description: "Sensor 8 port - Node type identifier. Possible values are in Table 57",
        scale: None,
        unit: None,
        enum_table: Some("table_57"),
    },
    FieldSpec {
        offset_bits: 568,
        length_bits: 8,
        name: "Abstract Node Type: Sensor 8",
        data_type: DataType::Enum,
        description: "Sensor 8 port - Abstract Node type identifier. Possible values are in Table 61",
        scale: None,
        unit: None,
        enum_table: Some("table_61"),
    },
    FieldSpec {
        offset_bits: 576,
        length_bits: 32,
        name: "Serial Number Integer: Sensor 8",
        data_type: DataType::Uint,
        description: "Sensor 8 port - Serial Number Integer Respresentation",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 608,
        length_bits: 32,
        name: "Address: Sensor 8",
        data_type: DataType::Uint,
        description: "Sensor 8 port - CAN Address",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 640,
        length_bits: 8,
        name: "Node Type: Wheel 1",
        data_type: DataType::Enum,
        description: "Wheel 1 port - Node type identifier. Possible values are in Table 57",
        scale: None,
        unit: None,
        enum_table: Some("table_57"),
    },
    FieldSpec {
        offset_bits: 648,
        length_bits: 8,
        name: "Abstract Node Type: Wheel 1",
        data_type: DataType::Enum,
        description: "Wheel 1 port - Abstract Node type identifier. Possible values are in Table 61",
        scale: None,
        unit: None,
        enum_table: Some("table_61"),
    },
    FieldSpec {
        offset_bits: 656,
        length_bits: 32,
        name: "Serial Number Integer: Wheel 1",
        data_type: DataType::Uint,
        description: "Wheel 1 port - Serial Number Integer Respresentation",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 688,
        length_bits: 32,
        name: "Address: Wheel 1",
        data_type: DataType::Uint,
        description: "Wheel 1 port - CAN Address",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 720,
        length_bits: 8,
        name: "Node Type: Wheel 2",
        data_type: DataType::Enum,
        description: "Wheel 2 port - Node type identifier. Possible values are in Table 57",
        scale: None,
        unit: None,
        enum_table: Some("table_57"),
    },
    FieldSpec {
        offset_bits: 728,
        length_bits: 8,
        name: "Abstract Node Type: Wheel 2",
        data_type: DataType::Enum,
        description: "Wheel 2 port - Abstract Node type identifier. Possible values are in Table 61",
        scale: None,
        unit: None,
        enum_table: Some("table_61"),
    },
    FieldSpec {
        offset_bits: 736,
        length_bits: 32,
        name: "Serial Number Integer: Wheel 2",
        data_type: DataType::Uint,
        description: "Wheel 2 port - Serial Number Integer Respresentation",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 768,
        length_bits: 32,
        name: "Address: Wheel 2",
        data_type: DataType::Uint,
        description: "Wheel 2 port - CAN Address",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 800,
        length_bits: 8,
        name: "Node Type: Wheel 3",
        data_type: DataType::Enum,
        description: "Wheel 3 port - Node type identifier. Possible values are in Table 57",
        scale: None,
        unit: None,
        enum_table: Some("table_57"),
    },
    FieldSpec {
        offset_bits: 808,
        length_bits: 8,
        name: "Abstract Node Type: Wheel 3",
        data_type: DataType::Enum,
        description: "Wheel 3 port - Abstract Node type identifier. Possible values are in Table 61",
        scale: None,
        unit: None,
        enum_table: Some("table_61"),
    },
    FieldSpec {
        offset_bits: 816,
        length_bits: 32,
        name: "Serial Number Integer: Wheel 3",
        data_type: DataType::Uint,
        description: "Wheel 3 port - Serial Number Integer Respresentation",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 848,
        length_bits: 32,
        name: "Address: Wheel 3",
        data_type: DataType::Uint,
        description: "Wheel 3 port - CAN Address",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 880,
        length_bits: 8,
        name: "Node Type: Wheel 4",
        data_type: DataType::Enum,
        description: "Wheel 4 port - Node type identifier. Possible values are in Table 57",
        scale: None,
        unit: None,
        enum_table: Some("table_57"),
    },
    FieldSpec {
        offset_bits: 888,
        length_bits: 8,
        name: "Abstract Node Type: Wheel 4",
        data_type: DataType::Enum,
        description: "Wheel 4 port - Abstract Node type identifier. Possible values are in Table 61",
        scale: None,
        unit: None,
        enum_table: Some("table_61"),
    },
    FieldSpec {
        offset_bits: 896,
        length_bits: 32,
        name: "Serial Number Integer: Wheel 4",
        data_type: DataType::Uint,
        description: "Wheel 4 port - Serial Number Integer Respresentation",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 928,
        length_bits: 32,
        name: "Address: Wheel 4",
        data_type: DataType::Uint,
        description: "Wheel 4 port - CAN Address",
        scale: None,
        unit: None,
        enum_table: None,
    },
];

const UNSOLICITED_TELEMETRY_SETUP_COMMAND_FIELDS: &[FieldSpec] = &[
    FieldSpec {
        offset_bits: 0,
        length_bits: 4,
        name: "UART Tlm Return Interval",
        data_type: DataType::Enum,
        description: "Indicate how frequently unsolicited telemetry is transmitted on the UART interface. Possible values are in Table 64",
        scale: None,
        unit: None,
        enum_table: Some("table_64"),
    },
    FieldSpec {
        offset_bits: 4,
        length_bits: 4,
        name: "UART2 Tlm Return Interval",
        data_type: DataType::Enum,
        description: "Indicate how frequently unsolicited telemetry is transmitted on the UART2 interface. Possible values are in Table 64",
        scale: None,
        unit: None,
        enum_table: Some("table_64"),
    },
    FieldSpec {
        offset_bits: 8,
        length_bits: 4,
        name: "CAN Tlm Return Interval",
        data_type: DataType::Enum,
        description: "Indicate how frequently unsolicited telemetry is transmitted on the CAN interface. Possible values are in Table 64",
        scale: None,
        unit: None,
        enum_table: Some("table_64"),
    },
    FieldSpec {
        offset_bits: 12,
        length_bits: 4,
        name: "Reserved",
        data_type: DataType::Padding,
        description: "Reserved.",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 16,
        length_bits: 40,
        name: "UART TLM ID inclusion bitmask",
        data_type: DataType::Array,
        description: "Indicate which TLM IDs must be included in the transfered Telemetry on the UART interface",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 56,
        length_bits: 40,
        name: "UART2 TLM ID inclusion bitmask",
        data_type: DataType::Array,
        description: "Indicate which TLM IDs must be included in the transfered Telemetry on the UART2 interface",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 96,
        length_bits: 40,
        name: "CAN TLM ID inclusion bitmask",
        data_type: DataType::Array,
        description: "Indicate which TLM IDs must be included in the transfered Telemetry on the CAN interface",
        scale: None,
        unit: None,
        enum_table: None,
    },
];

const SET_REQUEST_IMAGE_LOG_TRANSFER_SETUP_COMMAND_FIELDS: &[FieldSpec] = &[
    FieldSpec {
        offset_bits: 0,
        length_bits: 8,
        name: "Operation Code",
        data_type: DataType::Enum,
        description: "Operation code.. Possible values are in Table 67",
        scale: None,
        unit: None,
        enum_table: Some("table_67"),
    },
    FieldSpec {
        offset_bits: 8,
        length_bits: 8,
        name: "Target Node Type",
        data_type: DataType::Enum,
        description: "Target node type for image storage and download direct operation codes.. Possible values are in Table 61",
        scale: None,
        unit: None,
        enum_table: Some("table_61"),
    },
    FieldSpec {
        offset_bits: 16,
        length_bits: 32,
        name: "File Handle",
        data_type: DataType::Uint,
        description: "Target file for download and info operation codes.",
        scale: None,
        unit: None,
        enum_table: None,
    },
];

const SET_A_DUMMY_EVENT_COMMAND_FIELDS: &[FieldSpec] = &[
    FieldSpec {
        offset_bits: 0,
        length_bits: 2,
        name: "Event class",
        data_type: DataType::Enum,
        description: "This field contains the class of the event. Possible values are in Table 69",
        scale: None,
        unit: None,
        enum_table: Some("table_69"),
    },
    FieldSpec {
        offset_bits: 2,
        length_bits: 5,
        name: "Event source",
        data_type: DataType::Enum,
        description: "This field contains the source of the event. Possible values are in Table 61",
        scale: None,
        unit: None,
        enum_table: Some("table_61"),
    },
    FieldSpec {
        offset_bits: 7,
        length_bits: 1,
        name: "Reserved",
        data_type: DataType::Padding,
        description: "Reserved.",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 8,
        length_bits: 16,
        name: "Event type",
        data_type: DataType::Uint,
        description: "This field contains the type of the event",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 24,
        length_bits: 64,
        name: "Event data",
        data_type: DataType::Array,
        description: "This field contains the data of the event",
        scale: None,
        unit: None,
        enum_table: None,
    },
];

const UNSOLICITED_EVENT_MESSAGE_SETUP_COMMAND_FIELDS: &[FieldSpec] = &[
    FieldSpec {
        offset_bits: 0,
        length_bits: 1,
        name: "UART Info Events",
        data_type: DataType::Bool,
        description: "Output Info class events to UART",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 1,
        length_bits: 1,
        name: "UART Minor Warning Events",
        data_type: DataType::Bool,
        description: "Output minor warning class events to UART",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 2,
        length_bits: 1,
        name: "UART Major Warning Events",
        data_type: DataType::Bool,
        description: "Output major warning class events to UART",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 3,
        length_bits: 1,
        name: "UART Critical Events",
        data_type: DataType::Bool,
        description: "Output critical class events to UART2",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 4,
        length_bits: 1,
        name: "UART2 Info Events",
        data_type: DataType::Bool,
        description: "Output Info class events to UART2",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 5,
        length_bits: 1,
        name: "UART2 Minor Warning Events",
        data_type: DataType::Bool,
        description: "Output minor warning class events to UART2",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 6,
        length_bits: 1,
        name: "UART2 Major Warning Events",
        data_type: DataType::Bool,
        description: "Output major warning class events to UART2",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 7,
        length_bits: 1,
        name: "UART2 Critical Events",
        data_type: DataType::Bool,
        description: "Output critical class events to UART2",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 8,
        length_bits: 1,
        name: "CAN Info Events",
        data_type: DataType::Bool,
        description: "Output Info class events to CAN",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 9,
        length_bits: 1,
        name: "CAN Minor Warning Events",
        data_type: DataType::Bool,
        description: "Output minor warning class events to CAN",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 10,
        length_bits: 1,
        name: "CAN Major Warning Events",
        data_type: DataType::Bool,
        description: "Output major warning class events to CAN",
        scale: None,
        unit: None,
        enum_table: None,
    },
    FieldSpec {
        offset_bits: 11,
        length_bits: 1,
        name: "CAN Critical Events",
        data_type: DataType::Bool,
        description: "Output critical class events to CAN",
        scale: None,
        unit: None,
        enum_table: None,
    },
];

const FORMAT_ALL_LOGS_COMMAND_FIELDS: &[FieldSpec] = &[
    FieldSpec {
        offset_bits: 0,
        length_bits: 8,
        name: "Magic Number",
        data_type: DataType::Enum,
        description: "Magic number to avoid erroneous formats. Possible values are in Table 75",
        scale: None,
        unit: None,
        enum_table: Some("table_75"),
    },
];

/// Telecommand definitions present in the mission selection but omitted from the typed generator.
pub const ADDITIONAL_COMMAND_SPECS: &[CommandSpec] = &[
    CommandSpec {
        id: 40,
        name: "Reference Rotation Angle",
        purpose: "Offset rotation angle to rotate around in ConGndTrack, ConSatTrack, ConMoonTrack, ConIrcTrack",
        length_bytes: 4,
        fields: REFERENCE_ROTATION_ANGLE_COMMAND_FIELDS,
    },
    CommandSpec {
        id: 43,
        name: "Disable magnetic RWL momentum management",
        purpose: "Disable magnetic RWL momentum dumping",
        length_bytes: 2,
        fields: DISABLE_MAGNETIC_RWL_MOMENTUM_MANAGEMENT_COMMAND_FIELDS,
    },
    CommandSpec {
        id: 46,
        name: "Reference parameters for FMC scan",
        purpose: "Reference parameters for FMC scan",
        length_bytes: 13,
        fields: REFERENCE_PARAMETERS_FOR_FMC_SCAN_COMMAND_FIELDS,
    },
    CommandSpec {
        id: 47,
        name: "Reference IRC vector",
        purpose: "Reference IRC vector for inertial target tracking controller",
        length_bytes: 12,
        fields: REFERENCE_IRC_VECTOR_COMMAND_FIELDS,
    },
    CommandSpec {
        id: 48,
        name: "Reference LLH target command",
        purpose: "Reference target location for ground and target tracking controller",
        length_bytes: 12,
        fields: REFERENCE_LLH_TARGET_COMMAND_COMMAND_FIELDS,
    },
    CommandSpec {
        id: 60,
        name: "Target satellite orbit parameter configuration",
        purpose: "Satellite orbit parameter configuration",
        length_bytes: 64,
        fields: TARGET_SATELLITE_ORBIT_PARAMETER_CONFIGURATION_COMMAND_FIELDS,
    },
    CommandSpec {
        id: 73,
        name: "Simulation raw sensor telemetry",
        purpose: "Simulation raw sensor telemetry",
        length_bytes: 277,
        fields: SIMULATION_RAW_SENSOR_TELEMETRY_COMMAND_FIELDS,
    },
    CommandSpec {
        id: 79,
        name: "Transfer Frame",
        purpose: "Image frame to or from buffer",
        length_bytes: 2,
        fields: TRANSFER_FRAME_COMMAND_FIELDS,
    },
    CommandSpec {
        id: 80,
        name: "File Transfer Setup",
        purpose: "Setup a file transfer",
        length_bytes: 141,
        fields: FILE_TRANSFER_SETUP_COMMAND_FIELDS,
    },
    CommandSpec {
        id: 99,
        name: "Pass Through TCTLM",
        purpose: "TCTLM Passthrough settings",
        length_bytes: 1,
        fields: PASS_THROUGH_TCTLM_COMMAND_FIELDS,
    },
    CommandSpec {
        id: 111,
        name: "Port Map",
        purpose: "This telemetry describes the nodes that have been discovered i.e. connected to CubeConnect",
        length_bytes: 120,
        fields: PORT_MAP_COMMAND_FIELDS,
    },
    CommandSpec {
        id: 112,
        name: "Unsolicited Telemetry Setup",
        purpose: "Inclusion bitmask for unsolicited telemetry",
        length_bytes: 17,
        fields: UNSOLICITED_TELEMETRY_SETUP_COMMAND_FIELDS,
    },
    CommandSpec {
        id: 114,
        name: "Set Request Image Log Transfer Setup",
        purpose: "Set request image log transfer setup",
        length_bytes: 6,
        fields: SET_REQUEST_IMAGE_LOG_TRANSFER_SETUP_COMMAND_FIELDS,
    },
    CommandSpec {
        id: 115,
        name: "Set a dummy event",
        purpose: "Set a dummy event to be stored in the event log",
        length_bytes: 11,
        fields: SET_A_DUMMY_EVENT_COMMAND_FIELDS,
    },
    CommandSpec {
        id: 116,
        name: "Unsolicited Event Message Setup",
        purpose: "Setup unsolicited event messages",
        length_bytes: 2,
        fields: UNSOLICITED_EVENT_MESSAGE_SETUP_COMMAND_FIELDS,
    },
    CommandSpec {
        id: 122,
        name: "Format all logs",
        purpose: "Format all logs",
        length_bytes: 1,
        fields: FORMAT_ALL_LOGS_COMMAND_FIELDS,
    },
];
