[package]
name = "csp-service"
version = "0.1.0"
edition = "2024"


[dependencies]
kubos-service = { path = "../../kubos/services/kubos-service" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
juniper = "0.16.1"

[build-dependencies]
bindgen = "0.69"