[comms-services.addr]
ip = "0.0.0.0"
port = 8150

[comms-services.comms]
ip = "127.0.0.1"
timeout = 1500
max_num_handlers = 50
downlink_ports = [14011]

[comms-services.csp]
obc_node = 8
uplink_packet_csp_port = 10
uplink_sfp_csp_port = 12
ground_node = 2
ground_packet_csp_port = 11
ground_sfp_csp_port = 13
uplink_crypto = "none"
# uplink_crypto = "aes-128"
# uplink_aes_key = "000102030405060708090a0b0c0d0e0f"
sfp_mtu = 240
sfp_read_timeout_ms = 10000
sfp_use_rdp = true
sfp_max_space_packet_bytes = 65541
max_frame_bytes = 260

[comms-services.radios.uplink]
bus = "/dev/i2c-1"
csp_node = 15
i2c_addr = 15
slave_rx_device = "/dev/i2c-slave-frameq-1-08"
command_timeout_ms = 1000
# Optional NMP credentials. Replace the example values and uncomment them.
# nmp_user_key = 0x00000000
# nmp_superuser_key = 0x00000000

[comms-services.radios.downlink]
bus = "/dev/i2c-2"
csp_node = 9
i2c_addr = 9
command_timeout_ms = 1000
# nmp_user_key = 0x00000000
# nmp_superuser_key = 0x00000000
