---
# Git installation tasks

- name: "Install Git on Windows"
  chocolatey.chocolatey.win_chocolatey:
    name: git
    state: present
  when: ansible_os_family == "Windows"

- name: "Install Git on MacOS"
  community.general.homebrew_cask:
    name: git
    state: present
  when: ansible_os_family == "Darwin"

- name: "Install Git on Debian/Ubuntu"
  ansible.builtin.apt:
    name: git
    state: present
  when: ansible_os_family == "Debian" and pkg_mgr == "apt"

- name: "Install Git on RHEL/CentOS"
  ansible.builtin.yum:
    name: git
    state: present
  when: ansible_os_family == "RedHat" and pkg_mgr == "yum"

- name: "Install Git on Fedora"
  ansible.builtin.dnf:
    name: git
    state: present
  when: ansible_os_family == "RedHat" and pkg_mgr == "dnf"

- name: "Install Git on Arch Linux"
  community.general.pacman:
    name: git
    state: present
  when: ansible_os_family == "Archlinux" and pkg_mgr == "pacman"

- name: "Install Git on openSUSE"
  community.general.zypper:
    name: git
    state: present
  when: ansible_os_family == "Suse" and pkg_mgr == "zypper"
