---
# Windows-specific tasks

- name: Check if Chocolatey is installed
  ansible.windows.win_shell: |
    if (Get-Command choco -ErrorAction SilentlyContinue) {
      Write-Output "Chocolatey is already installed"
      exit 0
    } else {
      Write-Output "Chocolatey is not installed"
      exit 1
    }
  register: choco_check
  failed_when: false
  changed_when: choco_check.rc != 0

- name: Install Chocolatey
  ansible.windows.win_shell: |
    Set-ExecutionPolicy Bypass -Scope Process -Force
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
    iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
  when: choco_check.rc != 0
