[package]
name = "radio-api"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>, Oren Rotaru <oren.rotaru@usask.ca>"]
edition = "2018"

[dependencies]
nom = "4.0.0-beta1"
thiserror = "1.0.69"

[package.metadata.release]
release = false
